version: '3.3'
services:
  stagewood-auth-backend:
    build:
      context: ./stagewood-auth-system-backend/
      dockerfile: ./backend.dockerfile
    image: stagewood-auth-backend:latest
    environment:
      PRISMA_DS_URL: "mysql://stagewood-auth:SECRET@sw-db/stagewood-auth"
      APP_SECRET: "Jazy-is-aw3some"
    ports:
      - "4000:4000"

  stagewood-auth-frontend:
    build:
      context: ./stagewood-auth-system-frontend/
      dockerfile: ./frontend.dockerfile
      args:
        REACT_APP_HTTP_LINK_URL: "http://localhost:4001"
    image: stagewood-auth-frontend:latest
    ports:
      - "3000:80"

  sw-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: stagewood-auth
      MYSQL_USER: stagewood-auth
      MYSQL_PASSWORD: SECRET
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - "backend-db:/var/lib/mysql"
volumes:
  backend-db: